# Production docker-compose for Dokploy
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - PORT=8088
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8088/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.batch-app.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.batch-app.tls=true"
      - "traefik.http.routers.batch-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.batch-app.loadbalancer.server.port=8088"
